// GENERATED by scripts/generate-demo-data.ts — do not edit by hand.
//
// Captured output from one real pipeline run, frozen so that seeding the demo
// account costs zero model requests. That matters: the demo account exists as
// insurance for when the daily quota is gone, and a seed that called Gemini
// would fail in precisely that case.
//
// Regenerate with:
//   pnpm exec tsx --conditions=react-server --env-file=.env scripts/generate-demo-data.ts

import type { Analysis } from "@/lib/prompts/analyzer";
import type { Concept } from "@/lib/prompts/builder";

export const DEMO_PROJECT = {
  url: "https://linear.app/",
  description: "A lightweight issue tracker for one person, with all the team planning ceremony stripped out.",
  targetCustomer: "Indie developers shipping side projects at night",
} as const;

export const DEMO_ANALYSIS: Analysis = {
  "whatItDoes": "Linear is a project management platform designed for software teams to track issues, plan product roadmaps, and integrate AI agents into the development lifecycle. It synchronizes communication, code changes, and task status to help teams maintain velocity.",
  "targetUsers": [
    "Software engineering teams",
    "Product management teams",
    "Startups scaling development",
    "AI-native development teams"
  ],
  "coreProblem": "The product solves the fragmentation of information between planning, coding, and communication, which slows down development velocity. It centralizes these disparate workflows into a single system of record.",
  "keyFeatures": [
    "Issue tracking",
    "Cycle management",
    "AI agent integration",
    "Git/PR automation",
    "Project roadmaps",
    "Analytics dashboards"
  ],
  "businessModel": "Linear likely operates on a tiered SaaS subscription model, charging per user per month with higher tiers unlocking advanced features like AI agents, SSO, and deeper analytics.",
  "suggestedImprovements": [
    "Add a 'Focus Mode' that hides all project-level roadmap data to help individual contributors see only their immediate task list.",
    "Reduce the visual density of AI agent logs in the main issue view to keep human-readable comments more prominent.",
    "Simplify the initial onboarding flow for non-technical stakeholders who may find the 'system' terminology overwhelming."
  ],
  "mvpFeatures": [
    "Simple Kanban board with Todo, Doing, and Done states",
    "Markdown-based issue descriptions",
    "Keyboard-centric navigation for rapid entry",
    "Local-first data persistence",
    "Someday/Maybe backlog bucket"
  ]
};

/** The concept after every refinement below has been applied. */
export const DEMO_CONCEPT: Concept = {
  "name": "Soloist",
  "description": "Soloist is an artisanal issue tracker crafted exclusively for the solo developer. It replaces the noise of enterprise project management with a refined, high-fidelity environment designed for deep work and shipping side projects.",
  "features": [
    {
      "name": "Keyboard-first entry",
      "description": "Capture tasks instantly without touching your mouse using global shortcuts."
    },
    {
      "name": "Focus mode",
      "description": "Hide your entire backlog to see only the single task you are working on right now."
    },
    {
      "name": "Markdown editor",
      "description": "Write issue details and technical specs using clean, distraction-free markdown."
    },
    {
      "name": "Local-first storage",
      "description": "Your data lives on your machine, ensuring your project notes are always available offline."
    },
    {
      "name": "Someday bucket",
      "description": "Keep your active list clean by moving low-priority ideas into a hidden storage area."
    }
  ],
  "navigation": [
    {
      "label": "Dashboard",
      "path": "/dashboard"
    },
    {
      "label": "Backlog",
      "path": "/backlog"
    },
    {
      "label": "Pricing",
      "path": "/pricing"
    },
    {
      "label": "Settings",
      "path": "/settings"
    }
  ],
  "pages": [
    {
      "name": "Dashboard",
      "path": "/dashboard",
      "sections": [
        {
          "type": "hero",
          "headline": "What are you shipping tonight?",
          "body": "Your active queue is clear. Add a new task or pick one from your backlog to get started."
        },
        {
          "type": "list",
          "headline": "Active Tasks",
          "body": "These are the items you have committed to finishing in this session."
        }
      ]
    },
    {
      "name": "Backlog",
      "path": "/backlog",
      "sections": [
        {
          "type": "list",
          "headline": "The Someday Pile",
          "body": "All the ideas that are currently waiting for a better time. Keep them here so they don't clutter your mind."
        }
      ]
    },
    {
      "name": "Pricing",
      "path": "/pricing",
      "sections": [
        {
          "type": "pricing",
          "headline": "Simple, honest pricing",
          "body": "One flat fee for lifetime access. No subscriptions, no hidden costs, just the tools you need to build."
        }
      ]
    },
    {
      "name": "Settings",
      "path": "/settings",
      "sections": [
        {
          "type": "form",
          "headline": "Preferences",
          "body": "Configure your keyboard shortcuts and data export settings for your local database."
        },
        {
          "type": "faq",
          "headline": "Data Privacy",
          "body": "Soloist stores everything locally in your browser. We never see your project data."
        }
      ]
    }
  ],
  "uiDirection": {
    "style": "Editorial and spacious with generous whitespace",
    "mood": "Sophisticated, serene, and intentional",
    "typography": "Instrument Serif for headings, Inter for UI text",
    "palette": {
      "primary": "#1C1C1C",
      "surface": "#FFFFFF",
      "text": "#333333"
    }
  }
};

/** Oldest first. Each entry stores the full concept as it stood after that edit. */
export const DEMO_REFINEMENTS: { instruction: string; conceptAfter: Concept }[] = [
  {
    "instruction": "Make the design more premium.",
    "conceptAfter": {
      "name": "Soloist",
      "description": "Soloist is an artisanal issue tracker crafted exclusively for the solo developer. It replaces the noise of enterprise project management with a refined, high-fidelity environment designed for deep work and shipping side projects.",
      "features": [
        {
          "name": "Keyboard-first entry",
          "description": "Capture tasks instantly without touching your mouse using global shortcuts."
        },
        {
          "name": "Focus mode",
          "description": "Hide your entire backlog to see only the single task you are working on right now."
        },
        {
          "name": "Markdown editor",
          "description": "Write issue details and technical specs using clean, distraction-free markdown."
        },
        {
          "name": "Local-first storage",
          "description": "Your data lives on your machine, ensuring your project notes are always available offline."
        },
        {
          "name": "Someday bucket",
          "description": "Keep your active list clean by moving low-priority ideas into a hidden storage area."
        }
      ],
      "navigation": [
        {
          "label": "Dashboard",
          "path": "/dashboard"
        },
        {
          "label": "Backlog",
          "path": "/backlog"
        },
        {
          "label": "Settings",
          "path": "/settings"
        }
      ],
      "pages": [
        {
          "name": "Dashboard",
          "path": "/dashboard",
          "sections": [
            {
              "type": "hero",
              "headline": "What are you shipping tonight?",
              "body": "Your active queue is clear. Add a new task or pick one from your backlog to get started."
            },
            {
              "type": "list",
              "headline": "Active Tasks",
              "body": "These are the items you have committed to finishing in this session."
            }
          ]
        },
        {
          "name": "Backlog",
          "path": "/backlog",
          "sections": [
            {
              "type": "list",
              "headline": "The Someday Pile",
              "body": "All the ideas that are currently waiting for a better time. Keep them here so they don't clutter your mind."
            }
          ]
        },
        {
          "name": "Settings",
          "path": "/settings",
          "sections": [
            {
              "type": "form",
              "headline": "Preferences",
              "body": "Configure your keyboard shortcuts and data export settings for your local database."
            },
            {
              "type": "faq",
              "headline": "Data Privacy",
              "body": "Soloist stores everything locally in your browser. We never see your project data."
            }
          ]
        }
      ],
      "uiDirection": {
        "style": "Editorial and spacious with generous whitespace",
        "mood": "Sophisticated, serene, and intentional",
        "typography": "Instrument Serif for headings, Inter for UI text",
        "palette": {
          "primary": "#1C1C1C",
          "surface": "#FFFFFF",
          "text": "#333333"
        }
      }
    }
  },
  {
    "instruction": "Add a pricing page.",
    "conceptAfter": {
      "name": "Soloist",
      "description": "Soloist is an artisanal issue tracker crafted exclusively for the solo developer. It replaces the noise of enterprise project management with a refined, high-fidelity environment designed for deep work and shipping side projects.",
      "features": [
        {
          "name": "Keyboard-first entry",
          "description": "Capture tasks instantly without touching your mouse using global shortcuts."
        },
        {
          "name": "Focus mode",
          "description": "Hide your entire backlog to see only the single task you are working on right now."
        },
        {
          "name": "Markdown editor",
          "description": "Write issue details and technical specs using clean, distraction-free markdown."
        },
        {
          "name": "Local-first storage",
          "description": "Your data lives on your machine, ensuring your project notes are always available offline."
        },
        {
          "name": "Someday bucket",
          "description": "Keep your active list clean by moving low-priority ideas into a hidden storage area."
        }
      ],
      "navigation": [
        {
          "label": "Dashboard",
          "path": "/dashboard"
        },
        {
          "label": "Backlog",
          "path": "/backlog"
        },
        {
          "label": "Pricing",
          "path": "/pricing"
        },
        {
          "label": "Settings",
          "path": "/settings"
        }
      ],
      "pages": [
        {
          "name": "Dashboard",
          "path": "/dashboard",
          "sections": [
            {
              "type": "hero",
              "headline": "What are you shipping tonight?",
              "body": "Your active queue is clear. Add a new task or pick one from your backlog to get started."
            },
            {
              "type": "list",
              "headline": "Active Tasks",
              "body": "These are the items you have committed to finishing in this session."
            }
          ]
        },
        {
          "name": "Backlog",
          "path": "/backlog",
          "sections": [
            {
              "type": "list",
              "headline": "The Someday Pile",
              "body": "All the ideas that are currently waiting for a better time. Keep them here so they don't clutter your mind."
            }
          ]
        },
        {
          "name": "Pricing",
          "path": "/pricing",
          "sections": [
            {
              "type": "pricing",
              "headline": "Simple, honest pricing",
              "body": "One flat fee for lifetime access. No subscriptions, no hidden costs, just the tools you need to build."
            }
          ]
        },
        {
          "name": "Settings",
          "path": "/settings",
          "sections": [
            {
              "type": "form",
              "headline": "Preferences",
              "body": "Configure your keyboard shortcuts and data export settings for your local database."
            },
            {
              "type": "faq",
              "headline": "Data Privacy",
              "body": "Soloist stores everything locally in your browser. We never see your project data."
            }
          ]
        }
      ],
      "uiDirection": {
        "style": "Editorial and spacious with generous whitespace",
        "mood": "Sophisticated, serene, and intentional",
        "typography": "Instrument Serif for headings, Inter for UI text",
        "palette": {
          "primary": "#1C1C1C",
          "surface": "#FFFFFF",
          "text": "#333333"
        }
      }
    }
  }
];
