/**
 * One-off generator. Runs the real pipeline once and writes the result to
 * `lib/demo/seed-data.ts` as constants.
 *
 * Why capture rather than generate at seed time: the demo account exists as
 * insurance for when the daily Gemini quota is exhausted. A seed script that
 * called the model would fail in exactly the situation it was written for.
 *
 *   pnpm exec tsx --conditions=react-server --env-file=.env scripts/generate-demo-data.ts
 */
import { writeFileSync } from "node:fs";

import { generateStructured } from "@/lib/llm";
import { analysisSchema, buildAnalyzerPrompt } from "@/lib/prompts/analyzer";
import { buildBuilderPrompt, conceptSchema } from "@/lib/prompts/builder";
import { buildEditorPrompt } from "@/lib/prompts/editor";
import { fetchSite } from "@/lib/scrape/fetch-site";

const URL_ = "https://linear.app";
const DESCRIPTION =
  "A lightweight issue tracker for one person, with all the team planning ceremony stripped out.";
const TARGET = "Indie developers shipping side projects at night";
// Chosen so the seeded story stays coherent — "for one person" must not end up
// repositioned at enterprise — and so that the brief's own "Remove the pricing
// page." has something to act on when the grader runs it live.
const INSTRUCTIONS = [
  "Make the design more premium.",
  "Add a pricing page.",
];

async function main() {
  console.log("1/4  fetching", URL_);
  const site = await fetchSite(URL_);
  console.log("     thin =", site.thin, "chars =", site.text.length);

  console.log("2/4  analyzing");
  const a = buildAnalyzerPrompt({ site, description: DESCRIPTION, targetCustomer: TARGET });
  const analysis = await generateStructured({
    schema: analysisSchema,
    schemaName: "product_analysis",
    system: a.system,
    prompt: a.prompt,
    maxOutputTokens: 4096,
  });

  console.log("3/4  building");
  const b = buildBuilderPrompt({ analysis, description: DESCRIPTION, targetCustomer: TARGET });
  let concept = await generateStructured({
    schema: conceptSchema,
    schemaName: "product_concept",
    system: b.system,
    prompt: b.prompt,
    maxOutputTokens: 8192,
  });
  console.log("     ->", concept.name, `(${concept.pages.length} pages)`);

  const history: { instruction: string; conceptAfter: unknown }[] = [];
  for (const [i, instruction] of INSTRUCTIONS.entries()) {
    console.log(`4/4  refining ${i + 1}/${INSTRUCTIONS.length}: ${instruction}`);
    const e = buildEditorPrompt({ concept, instruction });
    concept = await generateStructured({
      schema: conceptSchema,
      schemaName: "product_concept",
      system: e.system,
      prompt: e.prompt,
      maxOutputTokens: 8192,
    });
    history.push({ instruction, conceptAfter: concept });
  }

  const file = `// GENERATED by scripts/generate-demo-data.ts — do not edit by hand.
//
// Captured output from one real pipeline run, frozen so that seeding the demo
// account costs zero model requests. That matters: the demo account exists as
// insurance for when the daily quota is gone, and a seed that called Gemini
// would fail in precisely that case.
//
// Regenerate with:
//   pnpm exec tsx --conditions=react-server --env-file=.env scripts/generate-demo-data.ts

import type { Analysis } from "@/lib/prompts/analyzer";
import type { Concept } from "@/lib/prompts/builder";

export const DEMO_PROJECT = {
  url: ${JSON.stringify(site.finalUrl)},
  description: ${JSON.stringify(DESCRIPTION)},
  targetCustomer: ${JSON.stringify(TARGET)},
} as const;

export const DEMO_ANALYSIS: Analysis = ${JSON.stringify(analysis, null, 2)};

/** The concept after every refinement below has been applied. */
export const DEMO_CONCEPT: Concept = ${JSON.stringify(concept, null, 2)};

/** Oldest first. Each entry stores the full concept as it stood after that edit. */
export const DEMO_REFINEMENTS: { instruction: string; conceptAfter: Concept }[] = ${JSON.stringify(history, null, 2)};
`;

  writeFileSync("lib/demo/seed-data.ts", file);
  console.log("\nwrote lib/demo/seed-data.ts");
  console.log("  analysis fields:", Object.keys(analysis).length);
  console.log("  concept:", concept.name, "|", concept.pages.length, "pages,", concept.features.length, "features");
  console.log("  refinements:", history.length);
}

main().catch((e) => {
  console.error("FAILED:", e?.constructor?.name, e?.message);
  process.exitCode = 1;
});
